{% set name = "pytest-bdd" %}
{% set version = "3.2.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17e73d2fe119de15bfc7fc1fe639fa4df9ab931e5aa552435fdddcf100c97ec5

build:
  noarch: python
  number: 0
  entry_points:
    - pytest-bdd = pytest_bdd.scripts:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - glob2
    - mako
    - parse
    - parse_type
    - py
    - pytest >=3.0.0
    - six >=1.9.0

test:
  imports:
    - pytest_bdd
  commands:
    - pytest-bdd --help

about:
  home: https://github.com/pytest-dev/pytest-bdd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: BDD for pytest
  description: "pytest-bdd implements a subset of the Gherkin language to enable automating project requirements testing and to facilitate behavioral driven development."
  dev_url: 'https://github.com/pytest-dev/pytest-bdd'
  doc_url: 'https://github.com/pytest-dev/pytest-bdd'

extra:
  recipe-maintainers: 
    - PertuyF
    - breathe
